### ISSUE TITLE
Check minimum django version

### ISSUE THREAD

**Issue by thclark** [octue/django-svelte-jsoneditor#5]
## Feature request

It wasn't that long ago that django implemented its own JSONField natively. Prior to that, JSONField was a postgres-specific contrib module, and many third party libraries sprang up to provide generic jsonfields.

We don't wish to support any of these, but we do wish to specify in `pyproject.toml` the minimum version of django which has the generic json field, so that this library isn't installable in setups using older versions of django.

**Comment by zehawki** [comment]
I'm unable to find this info anywhere - what is the minimum django version supported? Neither here https://pypi.org/project/django-svelte-jsoneditor/ nor https://django-svelte-jsoneditor.readthedocs.io/en/latest/
